version: '2'

services:
  traefik:
    image: traefik:1.6
    restart: always
    command: --api --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik

networks:
  default:
    external:
      name: thenetwork
