debug = true
logLevel = "ERROR" # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true 

defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

# Force https
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "beagle.lib.virginia.edu"
watch = true
# This will hide all docker containers that don't have explicitly set label to "enable"
exposedbydefault = false

[acme]
email = "scholars.lab@gmail.com"
storageFile = "acme.json"
acmeLogging = true
onDemand = false
onHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

